"""Generate claim links and a portable single-file journal manuscript source."""
from pathlib import Path
import csv,json,re,subprocess

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'results/revision_v4/stage3'


def flatten(path):
    text=path.read_text()
    return re.sub(r'\\input\{([^}]+)\}',lambda m:flatten(path.parent/(m[1]+('' if m[1].endswith('.tex') else '.tex'))),text)


def main():
    folder=ROOT/'paperV4/scientific_reports'
    source=flatten(folder/'main4.tex')
    source=source.replace('\\bibliography{references}',(folder/'main4.bbl').read_text())
    # Journal upload has separate figures and end legends. The author-review PDF
    # retains in-place figures for reading. Numerical/content source is identical.
    figures=re.findall(r'\\begin\{figure\}\[H\].*?\\end\{figure\}',source,re.S)
    for block in figures:source=source.replace(block,'')
    legends=[]
    for block in figures:
        legend=block[block.index('\\caption'):block.rindex('\\end{figure}')]
        legends.append('\\begin{figure}[H]\n'+legend+'\\end{figure}\n')
    tables=re.findall(r'\\begin\{table\}\[H\].*?\\end\{table\}',source,re.S)
    for block in tables:source=source.replace(block,'')
    source=source.replace('\\end{document}','\\section*{Figure legends}\n'+''.join(legends)+'\n\\section*{Tables}\n'+'\n'.join(tables)+'\n\\end{document}')
    source='% Generated from main4.tex and included sources by prepare_revision_v4_stage3_handoff.py.\n'+source
    (folder/'main4_submission.tex').write_text(source)
    # Source-linked claims. Audit results are independently reconstructed from raw
    # inputs; historical subgroup intervals retain the original stated method.
    rows=[]
    def claim(id,text,artifact,population,quantity,units,uncertainty,kind,limits,locations):
        rows.append(dict(id=id,claim=text,source_artifacts=artifact,population=population,quantity=quantity,units=units,uncertainty=uncertainty,evidence_class=kind,limitations=limits,manuscript_locations=locations))
    a='results/revision_v4/stage3/audit/'
    s='results/revision_v4/stage2/'
    claim('primary','Configured saved-token byte inversion',[a+'recovery.json','results/revision_v1/primary_v2'], '480 payloads, eight classes, three generators','6480/6480','payload trials','Wilson 95% intervals reported separately for trials and strict payload/model groups','retained experiment independently reconciled','Saved tokens and exact configuration held fixed. Repeated trials are not independent artifacts.','Abstract; main recovery Results; Supplementary S3; editor answer')
    claim('visible','Unmodified visible-retokenization recovery',[a+'recovery.json','results/revision_v1/robustness_v2'],'144 covers','88/144','cover payload endpoints','Wilson by cover','retained executed replay','Historical raw and limited unmodified aliases reference saved-ID endpoints with no new decode.','Abstract; robustness Results/Figure 3; Supplementary S4; R1.1')
    claim('transforms','Frozen transformations and cross-model failures',[a+'recovery.json'],'144 covers, two alternate decoders for cross-model','NFKC 82/144; quotes 56/144; trim 28/144; composite Markdown 0/144; paraphrase 0/144; cross-model 0/288 outcomes','cover or decoder outcomes as stated','Wilson cover intervals, 144 independent source covers for cross-model','retained executed replay','Specific operations and saved-offset extraction. No survey of Markdown workflows.','Abstract; robustness Results/Figure 3; Supplementary S4; R1.1/R1.3')
    for plan in ['pilot_initial','pilot_amendment1']:
        effects=json.loads((OUT/'audit/reconstructed_effects.json').read_text())
        vals=[r for r in effects if r['plan']==plan and r['model']=='all']
        claim(plan,'Control-only metric selection',[a+'reconstructed_effects.csv',s+'plans/'+plan,s+'raw'], '36 hash-selected identities, '+('36' if plan=='pilot_initial' else '35')+' recipient payload clusters',vals,'semantic cosine and nats/evaluator tail token','2000 percentile recipient-payload bootstrap draws stratified by artifact class','prospective control-only pilot','Both semantic intervals cross zero. Context gain passed the specified control-separation check. Single amendment, disjoint recipients and donors. No reader validation.','Boundary Results; Supplementary S17; R1.4; editor synthesis; cover letter')
    claim('boundary_selection','Structural-to-scored chain',[a+'boundary_counts.json',s+'plans/coherence_study/freeze.json'],'240 segmented payloads in four hex classes, broader ordinary donor corpus eight classes','8280 original; 92 selected payloads; 3174 selected structural; 2750 eligible; 550 scored trials; 8250 arm units','different nested units, never interchangeable','Identity-hash selection, 23/class before actual scoring','prospectively selected exploratory sample','552 planned trials, two have no eligible boundary. Mistral excludes 341/1058, Llama 43/1058, Qwen 40/1058.','Boundary Methods/Results; Supplementary S17; R1.4')
    vals=[r for r in effects if r['plan']=='coherence_study']
    claim('context_gain','Limited fixed-path local compatibility',[a+'reconstructed_effects.csv',s+'raw',s+'plans/coherence_study/unit_requests.jsonl'],'92 recipient payloads, 550 trials, 2750 boundaries',vals,'nats per evaluator tail token','2000 shared stratified recipient-payload draws after segment then trial aggregation','exploratory retained-score study independently recomputed','Intervals condition on fixed donors. Sampled ordinary versus greedy actual tails confounds boundary effect. Mistral and Qwen secondary raw-likelihood intervals include zero.','Main boundary table; Supplementary subgroup table and figure; abstract; discussion; R1.4; cover letter')
    claim('fixed_tail_path','Conditional and reference share targets',[a+'boundary_counts.json',s+'plans/coherence_study/units.jsonl',s+'raw'],'8250 arm units','3057 standalone-right tokenizations differ','scoring units','Descriptive complete-unit count','implementation and retained input audit','Joint evaluator left/right tokenization with straddles excluded. P+L and P score same suffix IDs, not independently retokenized strings.','Equation 17; boundary Methods; Supplementary S17; R1.4')
    claim('donors','Reference support and influence',[a+'boundary_counts.json',s+'analysis/coherence_study/donor_sensitivity.csv'],'2750 paired boundaries','ordinary 411 payloads/2398 identities max reuse 18/2; shuffled 240/2354 max 32/4; G leave-one ranges .1504-.1643 and 2.3210-2.3363','payloads, source identities and effect ranges','Leave-one-donor ranges are influence diagnostics, not population confidence intervals','fixed-corpus sensitivity','Primary intervals omit random donor-corpus uncertainty. No broad donor-population inference.','Supplementary S17; R1.4')
    claim('examples','Metric-ranked examples preserve adverse wording',[a+'examples.json',s+'analysis/coherence_study/examples.json'],'all 2750 eligible actual units','G -0.2986, 1.8772, 7.7527','nats/evaluator tail token','Minimum, upper-middle, maximum with SHA256 identity tie rule','predeclared illustration','Strong means score only. Highest example contains over|much and malformed wording.','Supplementary S17; R1.4')
    claim('transport','Illustrative decomposed transport recovery',[a+'transport.json',s+'transport/segment_diagnostics.jsonl'],'five identity-selected source covers, no eligible Mistral success','25 logical arms; 135 segment instances; 26 new requests; 53 capacity checks; prefix/outer/trailing/LF/unwrap successes 0/1/1/2/1 of five','logical covers and computational requests distinguished','No population intervals for this mechanism selection','bounded diagnostic experiment','All 27 prefix instances reject first forced token. No downstream avalanche observed. No general repair claim.','Transport Results; Supplementary S18; R1.1')
    claim('quantization','Q4 path replayed with saved Q8 ranks',[a+'quantization.json','results/revision_v3/generation/raw/quantization',s+'quantization/q4_to_q8_fixed_message_decode.jsonl'],'960 encoded plus 960 ordinary shared-history pairs','encoded 56321/122220 changed ranks; ordinary 13207/122220; exact bytes 0/960; invalid ranks 766; accepted wrong bytes 194','positions and payload trials distinguished','Descriptive census of retained pairs','offline byte reconstruction independently implemented','One Qwen revision. No reverse-direction decoding. Accepted decoder strips padding unchecked, including one wrong case with nonzero terminal padding.','Fixed-message Results; Supplementary S14/S18/S19; abstract; R1.10; cover letter')
    claim('entropy','Six original strict failures and comparators',[a+'entropy.json','results/revision_v4/source_tables/entropy_positions.csv','results/revision_v4/source_tables/entropy_text_windows.csv',s+'entropy/failure_comparators.csv'],'120 strict attempts, six failures, 12 matched ungated/moderate plus three selected strict-success comparators','114/120 completion; requested/consumed 128/110,128/116,64/54,128/106,128/59,128/116; budgets 768 except384; longest runs50,163,39,35,267,51','payload attempts, token positions','Descriptive retained trajectories and matched comparators','offline trace audit','Unfiltered, ordinary sampled skips. Text contexts do not identify causes. Successes also contain low-entropy runs.','Gate Results and table; Supplementary S13/S16 exact windows; R1.6')
    claim('serialized_rate','Entropy rate definition',[s+'entropy/serialized_rate_audit.json','rankcloak/revision_v3_generation.py'],'120/120/114 completed ungated/moderate/strict trials','7.4001/5.7920/4.0513','8 times serialized payload bytes/generated tokens','Conditioned on completion, not all-attempt capacity','retained accounting','Not Shannon capacity or four-bits-per-hex-character artifact accounting.','Gate Methods/Results table; Supplementary S13; R1.6')
    claim('detector','Trace-informed discrimination and access',[a+'linkage.json','results/revision_v3/detector_predictions','rankcloak/revision_v3_analysis.py','revision_docs/REVISION_V4_STAGE2_THEORY.md'],'strict matched test 1491 positives and1491 negatives','TextCNN AUC .9868; DeBERTa .9994; trace-informed .999995','ROC-AUC','2000 deduplication-cluster percentile draws in retained analysis','retained statistical evidence and theory','Saved original IDs, scores, exact model/backend/prompts/resets. Untempered scoring differs from top-p sampling. AUC not KL. Full receiver configuration may decode.','Detector Results/Figure5; discussion; abstract; R1.5')
    claim('filter','Exact unchanged filtering and ordering',['rankcloak/token_filters.py','rankcloak/rank_codec.py','results/revision_v4/provenance/filter_contract.json'],'individually decoded vocabulary pieces','Complete literal rules in main Methods','deterministic rules','No statistical uncertainty','source-code contract','Concatenated text need not inherit isolated safety or roundtrip stability. Special-token sampling exclusions separate.','Main Methods Table1; R1.9')
    claim('theory','Costs, configuration sensitivity and rank margins',['revision_docs/REVISION_V4_STAGE2_THEORY.md',s+'provenance/primary_sources/manifest.json','rankcloak/revision_v4_compatibility.py'],'declared fixed-history/mask/order model and algorithm implementations','selection O(V+A log A); rank counting O(V+A); uniform 2epsilon sufficient pairwise gap','operation counts and sufficient bounds','Conditional proofs, not observed timing superiority or estimated epsilon','theory and code inspection','Model calls, prefills, repeated sorts, probability passes, KV/logits_all, tails/skips, direct-subword passes included.','Overhead/discussion; Supplementary S19; R1.2/R1.7/R1.10')
    claim('fallback','Independent blocks, integrity, ECC, retransmission',['revision_docs/REVISION_V4_STAGE2_THEORY.md'],'hypothetical correctly framed supported configuration','2e+s<d sufficient unique correction condition','errors and located erasures','Theoretical channel assumptions','unimplemented proposal','Cannot repair arbitrary wrong codebook or persistent synchronization loss. Compatibility header not authentication.','Discussion; Supplementary S19; R1.3')
    claim('bibliography','Entropy threshold precedent',['revision_docs/REFERENCE_AUDIT.md','revision_docs/REVISION_V4_STAGE2_THEORY.md','paperV4/scientific_reports/references.bib'],'former reference16 Cai2025EntropyGuidedWatermarking','Lee2024SWEET ACL2024 replaces its active role','citation claim scope','Primary publication metadata verified','source audit','Watermark detection is not arbitrary payload recovery. Cai remains an unused historical bibliography entry.','Introduction; Supplementary S13; R1.8')
    claim('archive','Published deposit does not cover V4',['results/revision_v4/provenance/archive_v2_coverage.json','results/revision_v4/stage3/provenance/zenodo_v2.json','release/v4/assembly_policy.json'],'published2.0.0 DOI22555497','8342 archived files,65paperV3,zeroV4,source ce853d42d6ba64065cb63c6bdfc0d825c62734cd','archive members','Archive checksum and inventory verification','published-record audit','Local verified V4 candidate is separate. Final public DOI and document update remain.','Availability; archive response; cover letter; checklist')
    (OUT/'claim_evidence.json').write_text(json.dumps({'schema':'rankcloak.stage3.claims.v1','claims':rows},indent=2)+'\n')
    table=['# V4 claim-to-evidence ledger','','Full quantities, uncertainty methods and source paths are in claim_evidence.json. Independent reconstructions are in audit/.','','| Claim | Population and quantity | Evidence class | Uncertainty and limitation |','| --- | --- | --- | --- |']
    for r in rows:
        quantity=r['quantity'] if isinstance(r['quantity'],str) else 'All effects and intervals in audit/reconstructed_effects.csv'
        table.append('| '+r['id']+' | '+r['population']+'. '+quantity+' | '+r['evidence_class']+' | '+r['uncertainty']+'. '+r['limitations']+' |')
    (OUT/'CLAIM_EVIDENCE.md').write_text('\n'.join(table)+'\n')


if __name__=='__main__':main()
